# golangci-lint 配置文件
# 用于 Go 代码静态分析，确保代码质量和一致性
# 项目: YB Migration - MySQL 到 YB 数据库迁移兼容性分析工具
# 版本: 2 (兼容 golangci-lint v1.50+)
# 最后更新: 2025-02-03
version: 2

# ============================================================================
# 运行配置 (Run Configuration)
# ============================================================================
run:
  # 超时设置：5分钟（适用于大型项目）
  # 默认值: 1m | 最佳实践: 5m
  # 说明: 对于大型项目或复杂分析，5分钟通常足够，避免因网络或性能问题导致超时
  timeout: 5m
  
  # 模块下载模式：只读，避免意外修改 go.mod
  # 默认值: readonly | 最佳实践: readonly
  # 说明: readonly 模式确保 CI/CD 过程中不会意外修改依赖，保持构建一致性
  modules-download-mode: readonly
  
  # 允许并行运行：CI 中并行执行优化
  # 默认值: false | 最佳实践: true
  # 说明: 启用并行运行可以显著提高检查速度，特别是在 CI/CD 环境中
  allow-parallel-runners: true
  
  # 跳过目录：排除生成的文件和第三方代码
  # 默认值: [] | 最佳实践: 根据项目需要
  # 说明: 这些目录通常不需要检查，包含第三方代码或生成的文件
  skip-dirs:
    - vendor          # 第三方依赖，由供应商管理
    - testdata        # 测试数据文件
    - .git            # Git 版本控制文件
    - bin             # 编译输出目录
    - output-report   # 报告输出目录
  
  # 跳过文件：排除生成的文件
  # 默认值: [] | 最佳实践: 根据项目需要
  # 说明: 生成的文件通常不符合人工编码规范，应该排除检查
  skip-files:
    - ".*\\.pb\\.go$"      # Protocol Buffers 生成的文件
    - ".*_generated\\.go$" # 其他工具生成的文件
    - ".*_mock\\.go$"      # Mock 测试文件

# ============================================================================
# 启用的 Linters 列表 (Enabled Linters)
# ============================================================================
linters:
  enable:
    # ========================================================================
    # 基础检查 (Basic Checks) - Go 官方和核心工具
    # ========================================================================
    - govet          # Go 官方静态分析工具，检查常见错误（如 nil 指针、未初始化变量等）
    - errcheck       # 检查未处理的错误返回值，确保错误处理完整性
    - staticcheck    # 静态分析，检查 bug、性能问题、不正确用法等高级问题
    
    # ========================================================================
    # 代码风格和格式 (Code Style & Formatting)
    # ========================================================================
    - revive         # Go 替代 golint 的代码风格检查器，规则更灵活可配置
    - ineffassign    # 检查无效赋值（赋值后未使用的变量）
    - unused         # 检查未使用的变量、函数、常量等，帮助清理代码
    - misspell       # 检查拼写错误，提高代码可读性
    - whitespace     # 检查空白字符问题，确保格式一致性
    
    # ========================================================================
    # 复杂度检查 (Complexity Checks) - 控制代码复杂度，提高可维护性
    # ========================================================================
    - gocyclo        # 圈复杂度检查（Cyclomatic Complexity），衡量代码路径复杂度
    - gocognit       # 认知复杂度检查（Cognitive Complexity），衡量代码理解难度
    
    # ========================================================================
    # 代码质量 (Code Quality) - 提升代码质量和一致性
    # ========================================================================
    - dupl           # 代码重复检查器，发现重复代码促进重构
    - goconst        # 检查可以提取为常量的字符串，提高代码复用性
    - gocritic       # Go 代码质量检查器，包含多种最佳实践检查
    - mnd            # 魔法数字检查，建议使用命名常量替代硬编码数字
    - gomoddirectives # 检查 go.mod 指令的正确性
    - gomodguard     # 检查 go.mod 依赖，防止不安全的依赖
    - goprintffuncname # 检查 printf 函数名格式，确保日志一致性
    - nolintlint     # 检查 nolint 指令的正确性，避免滥用
    - rowserrcheck   # 检查数据库 rows.Close() 错误，防止资源泄漏
    - sqlclosecheck  # 检查数据库连接关闭，防止连接泄漏
    - unconvert      # 检查不必要的类型转换，简化代码
    - unparam        # 检查未使用的函数参数，帮助清理接口
    - nakedret       # 检查裸返回语句，建议明确返回值
    - predeclared    # 检查预声明标识符的阴影
    
    # ========================================================================
    # 安全性检查 (Security Checks) - 发现潜在安全漏洞
    # ========================================================================
    - gosec          # 安全漏洞检查，发现常见安全问题（如 SQL 注入、路径遍历等）
    - forcetypeassert # 强制类型断言检查，避免 panic 风险
    
    # ========================================================================
    # 性能检查 (Performance Checks) - 优化代码性能
    # ========================================================================
    - prealloc       # 检查 slice 预分配优化，减少内存重分配
    - bodyclose      # 检查 HTTP 响应体关闭，防止资源泄漏
    
  # ========================================================================
  # 禁用的 Linters (Disabled Linters) - 简化配置，专注核心质量
  # ========================================================================
  disable:
    # - exhaustruct    # 结构体字段完整性检查（过于严格）
    # - gochecknoglobals # 全局变量检查（项目有合理使用）
    # - lll             # 行长度检查（Go 社区不强制）
    # - wsl             # 空白敏感检查（与项目风格冲突）
    # - err113         # 错误处理检查（过于严格）


# ============================================================================
# Linters 详细设置 (Linters Settings) - 最佳实践配置
# ============================================================================
linters-settings:
  # ========================================================================
  # 圈复杂度设置 (Cyclomatic Complexity)
  # ========================================================================
  gocyclo:
    # 最小复杂度阈值（超过此值会报告）
    # 默认值: 30 | 最佳实践: 10-20
    # 说明: 圈复杂度衡量代码中的独立路径数量，20 是平衡可读性和复杂度的合理值
    min-complexity: 20
    
  # ========================================================================
  # 认知复杂度设置 (Cognitive Complexity)
  # ========================================================================
  gocognit:
    # 最小认知复杂度阈值（超过此值会报告）
    # 默认值: 30 | 最佳实践: 10-20
    # 说明: 认知复杂度衡量代码理解难度，考虑嵌套、逻辑运算等，40 适应复杂业务逻辑
    min-complexity: 20
    
  # ========================================================================
  # 代码质量检查器设置 (Code Quality Linters Settings)
  # ========================================================================
  dupl:
    # 代码重复阈值，超过此值会报告
    # 默认值: 150 | 最佳实践: 100-200
    # 说明: 降低阈值以更早发现重复代码，促进重构
    threshold: 150
    
  goconst:
    # 最小字符串长度，超过此长度的重复字符串会被检查
    # 默认值: 3 | 最佳实践: 2-5
    # 说明: 降低阈值以发现更多可提取为常量的字符串
    min-len: 3
    # 最小出现次数，超过此次数的重复字符串会被检查
    # 默认值: 3 | 最佳实践: 2-4
    # 说明: 降低阈值以更早发现重复字符串
    min-occurrences: 3
    # 忽略测试文件
    # 默认值: false | 最佳实践: true
    # 说明: 测试文件中的重复字符串通常可以接受
    ignore-tests: true
    
  mnd:
    # 要检查的魔法数字类型
    # 默认值: [argument, case, condition, operation, return, assign]
    # 说明: 检查各种上下文中的魔法数字
    checks:
      - argument    # 函数参数中的数字
      - case        # case 语句中的数字
      - condition   # 条件表达式中的数字
      - operation   # 操作中的数字
      - return      # 返回值中的数字
      - assign      # 赋值语句中的数字
    # 忽略的数字列表
    # 默认值: ["1", "0", "2", "1.0", "0.0"]
    # 说明: 忽略常见的数字，如 0, 1, 2 等
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "10"
      - "100"
      - "1000"
    
  misspell:
    # 拼写检查地区设置
    # 默认值: "" (中性) | 最佳实践: US
    # 说明: 使用美式拼写检查
    locale: US
    # 忽略的单词列表
    # 默认值: [] | 最佳实践: 项目特定词汇
    # 说明: 忽略项目中的专有词汇或缩写
    ignore-words:
      - "yb"      # 项目名称
    
  nakedret:
    # 允许裸返回的最大函数行数
    # 默认值: 30 | 最佳实践: 10-20
    # 说明: 超过此行数的函数不应使用裸返回
    max-func-lines: 15
    
  predeclared:
    # 检查预声明标识符的阴影
    # 默认值: false | 最佳实践: true
    # 说明: 防止变量名与预声明标识符冲突
    check: true
    # 包含方法名和字段名的检查
    # 默认值: false | 最佳实践: true
    # 说明: 检查方法名和字段名是否与预声明标识符冲突
    q: true
    
  # ========================================================================
  # revive 规则设置 (Code Style Rules)
  # ========================================================================
  revive:
    # 忽略生成的文件头部
    # 默认值: false | 最佳实践: true
    # 说明: 生成的文件通常不需要包注释，设置为 true 避免误报
    ignoreGeneratedHeader: true
    # 配置规则
    rules:
      # 导出规则：检查导出的函数、变量等命名规范
      - name: exported
        # 严重程度: error, warning, ignore
        # 默认值: warning | 最佳实践: warning
        severity: warning
        # 是否禁用规则
        # 默认值: false | 最佳实践: false
        disabled: false
        
      # 变量命名规则：检查变量命名规范
      - name: var-naming
        # 默认值: warning | 最佳实践: warning
        severity: warning
        disabled: false
          
      # 函数返回值数量限制
      - name: function-result-limit
        # 默认值: warning | 最佳实践: warning
        severity: warning
        disabled: false
        # 最大返回值数量
        # 默认值: 3 | 最佳实践: 3-4
        # 说明: 最多4个返回值，超过建议使用结构体
        arguments: [4]
    
  # ========================================================================
  # gosec 设置 (Security Checks)
  # ========================================================================
  gosec:
    # 排除过于严格的检查
    # 默认值: [] | 最佳实践: ["G601"]
    # 说明: G601 可能误报的隐式内存别名，排除以减少误报
    excludes:
      - G601  # 可能误报的隐式内存别名
    
  # ========================================================================
  # errcheck 设置 (Error Checking)
  # ========================================================================
  errcheck:
    # 忽略的函数（包级别）
    # 默认值: [] | 最佳实践: 根据项目需要
    # 说明: 这些库的函数通常有合理的错误处理机制，可以忽略检查
    ignore: fmt:.*,os:.*,io:.*,log:.*,encoding/json:.*,time:.*
    # 忽略的函数（具体函数）
    # 默认值: [] | 最佳实践: 根据项目需要
    # 说明: 这些函数的错误处理通常是可选的或由调用者决定
    ignore-functions: os.Exit,fmt.Print,fmt.Printf,fmt.Println,log.Print,log.Printf,log.Println
    
  # ========================================================================
  # govet 设置 (Go Vet)
  # ========================================================================
  govet:
    # 启用所有检查器
    # 默认值: false | 最佳实践: true
    # 说明: 启用所有可用的检查器，确保代码质量
    enable-all: true
    # 禁用的检查器
    # 默认值: [] | 最佳实践: ["fieldalignment"]
    # 说明: fieldalignment 可能过于严格，影响代码可读性
    disable:
      - fieldalignment
    
  # ========================================================================
  # prealloc 设置 (Preallocation Check)
  # ========================================================================
  prealloc:
    # 检查简单循环
    # 默认值: true | 最佳实践: true
    # 说明: 检查简单循环中的 slice 预分配优化
    simple: true
    # 检查范围循环
    # 默认值: true | 最佳实践: true
    # 说明: 检查 range 循环中的 slice 预分配
    range-loops: true
    # 检查 for 循环
    # 默认值: false | 最佳实践: false
    # 说明: for 循环的预分配检查可能产生误报
    for-loops: false
    

# ============================================================================
# 代码格式化器 (Code Formatters)
# ============================================================================
formatters:
  # 启用的格式化器
  # 默认值: [] | 最佳实践: ["gci", "gofmt"]
  # 说明: 使用 gci 替代 goimports，更好地处理导入分组空行问题
  enable:
    - gci           # Go import 排序和分组工具，更灵活的 import 管理
    - gofmt         # Go 标准代码格式化工具
    # - goimports     # 暂时禁用，避免与 gci 冲突
  # 格式化器设置
  settings:
    goimports:
      # 本地包前缀
      # 默认值: "" | 最佳实践: "github.com/example/ybMigration"
      # 说明: 指定项目模块路径，确保本地 import 正确分组
      local-prefixes: github.com/example/ybMigration
    
    gci:
      # 导入分组配置
      # 默认值: ["standard", "default"] | 最佳实践: ["standard", "default", "prefix(github.com/example/ybMigration)"]
      # 说明: 定义导入分组顺序和规则
      sections:
        - standard      # 标准库导入
        - default       # 第三方库导入
        - prefix(github.com/example/ybMigration)  # 项目内部导入
      # 分组间插入空行
      # 默认值: false | 最佳实践: true
      # 说明: 在不同导入分组之间插入空行，提高可读性
      section-separators: true

# ============================================================================
# 问题配置 (Issues Configuration)
# ============================================================================
issues:
  # 每个 linter 的最大问题数（0 表示不限制）
  # 默认值: 50 | 最佳实践: 0
  # 说明: 不限制问题数量，确保发现所有潜在问题
  max-issues-per-linter: 0
  # 相同问题的最大数量（0 表示不限制）
  # 默认值: 3 | 最佳实践: 0
  # 说明: 不限制相同问题的数量，避免遗漏重复问题
  max-same-issues: 0
  # 显示统计信息
  # 默认值: false | 最佳实践: true
  # 说明: 在输出中显示统计信息，便于了解问题分布
  show-stats: true
  
  # ========================================================================
  # 排除规则 (Exclusion Rules) - 简化版本，专注核心问题
  # ========================================================================
  exclude-rules:
    # 测试文件的宽松规则 - 排除所有测试文件的问题检查
    # 默认值: [] | 最佳实践: 根据项目需要
    - path: _test\.go$
      linters:
        - gocyclo            # 允许测试函数有更高圈复杂度
        - gocognit           # 允许测试函数有更高认知复杂度
        # - errcheck           # 允许测试中忽略某些 error
        # - gosec              # 允许测试中使用不安全的代码
        # - goconst            # 允许测试中的重复字符串
        # - mnd                # 允许测试中的魔法数字
        # - dupl               # 允许测试中的重复代码
        # - revive             # 放宽命名规范
        # - forcetypeassert    # 允许测试中的强制类型断言
        # - bodyclose          # 允许测试中不关闭响应体
        # - gci                # 允许测试文件的 import 格式
        # - goimports          # 允许测试文件的格式
    
      
  # 是否使用默认排除规则
  # 默认值: true | 最佳实践: true
  # 说明: 启用默认排除规则，结合自定义排除逻辑，提供更全面的误报过滤
  exclude-use-default: true
  
  # 新问题检查（仅在新代码中检查）
  # 默认值: false | 最佳实践: false
  # 说明: 检查所有代码，不仅仅是新增的代码
  new: false

# ============================================================================
# 输出配置 (Output Configuration)
# ============================================================================
output:
  # 打印 linter 名称
  # 默认值: true | 最佳实践: true
  # 说明: 在输出中显示问题来自哪个 linter，便于调试
  print-linter-name: true
  
  # 打印问题行号
  # 默认值: true | 最佳实践: true
  # 说明: 在输出中显示问题的具体行号，便于定位
  print-issued-lines: true
  
  # 使用颜色
  # 默认值: auto | 最佳实践: true
  # 说明: 在终端输出中使用颜色，提高可读性
  colors: true
  
  # 排序方式
  # 默认值: false | 最佳实践: true
  # 说明: 对输出结果进行排序，便于查看
  sort-results: true
  
  # 输出格式配置
  # 默认值: colored-line-number | 最佳实践: colored-line-number
  # 说明: 使用带颜色的行号格式，便于在终端中查看
  formats:
    colored-line-number: true
    # text:
    #   path: lint-report.txt
    # json:
    #   path: lint-report.json
    html:
      path: lint-report.html